### ISSUE TITLE
What a good boy

### ISSUE THREAD

**Issue by Gabriel55ita** [xeondev1337/scdocs#3]
Have a great day!

P.S: if you can make a Java version of Bitstream would be awesome.

**Comment by BreadBSS** [comment]
я делаю javnik bitstrim но не give it

**Comment by RomashkaTea** [comment]
дай пж.

**Comment by RomashkaTea** [comment]
а все не надо.

**Comment by RomashkaTea** [comment]
у меня есть но не дам 21г48921а89ып89фпо8фы9поф
